### PR TITLE
Add  src directory

### PR DESCRIPTION
**Pull request by principles31**
## Does my coding partner follow JS best practices?
- A complete To-Do-List project for Review Based on 
- JavaScript best practices.
- DRY, KISS, and YAGNI rules.
- HTML & CSS best practices

### CODE REVIEW

**Comment by felixodette** [comment]
Great job on the project. Kudos for:

* Keeping your JS code to best practices
* Observing DRY, KISS, and YAGNI rules

However, you might want to consider implementing HTML5 semantic code for the following section (perhaps incorporate header, main, and/or footer sections):

```
[<body>
  <section class="todolist">
    <div class="todo-header">
      <h3>Today's To Do</h3>
      <a href="#"><i id="reset" class="fa fa fa-refresh"></i></a>
    </div>
    <div class="todo-form">
      <form id="form">
        <input class="new-task" type="text" placeholder=" Add your list..." minlength="2">
        <button class="submit" type="submit">&crarr;</button>
      </form>
    </div>
    <div class="todo-form">
      <!-- dynamically generated -->
    </div>
    <button class="clear-all">Clear all completed</button>
  </section>
</body>](https://github.com/principles31/Code_Review/blob/e2f3e49efd0c4246fb75f90d0e8d13f985dd5a68/src/index.html#L11-L29)
```

**Comment by principles31** [comment]
@felixodette Thanks for the feedback.

**Review by principles31 — COMMENTED** [review]
- Header section has been added as requested by the reviewer.

**Comment by felixodette** [comment]
The Pull Request has a proper title and description. ✔️
You have added a descriptive Readme file. Good Job. ✔️
There is no linter error is present. ✔️
The project has met all the technical aspects you needed for this project. Keep rocking! ✔️


Cheers and Happy coding!👏👏👏

**Pull request merged**
